#Requires AutoHotkey v2.0
; Auto-generated by AutoFire - DO NOT EDIT MANUALLY
; This script is automatically updated when you click Start in the AutoFire UI

TriggerKey := "``"
OutputKey := "e"
IntervalMs := 100
PassThrough := false

IsRunning := false

; Emergency stop hotkey (Ctrl+Alt+Esc)
^!Esc::{
    if (IsRunning) {
        IsRunning := false
    }
    ExitApp
}

; Register trigger key hotkey
if (PassThrough) {
    ; Pass-through mode: trigger key reaches the game
    Hotkey "~$" TriggerKey, TriggerPress
    Hotkey "~$" TriggerKey " up", TriggerRelease
} else {
    ; Block mode: trigger key is suppressed
    Hotkey "$" TriggerKey, TriggerPress
    Hotkey "$" TriggerKey " up", TriggerRelease
}

TriggerPress(*) {
    global IsRunning
    if (IsRunning) {
        return  ; Already running
    }
    IsRunning := true
    ; Start the autofire loop in a new thread so the hotkey can return
    SetTimer AutoFireLoop, -1
}

TriggerRelease(*) {
    global IsRunning
    IsRunning := false
}

AutoFireLoop() {
    global IsRunning, OutputKey, IntervalMs
    
    While IsRunning {
        ; Send the key down
        SendInput "{" OutputKey " down}"
        
        ; Wait a random short time (15-45ms) for the "up" stroke to look more human
        r_down_time := Random(15, 45)
        Sleep r_down_time
        
        ; Send the key up
        SendInput "{" OutputKey " up}"
        
        ; Wait for the main interval, plus a small random variation (-10ms to +20ms)
        r_interval_variance := Random(-10, 20)
        wait_time := IntervalMs + r_interval_variance
        
        ; Ensure we don't sleep for a negative or tiny amount if interval is low
        if (wait_time < 15) {
            wait_time := 15
        }
        Sleep wait_time
    }
}
